// Contains the initial, or seed data.
const tattoos = [
    {
        title: "Oceanic Dream",
        description: "A beautiful tattoo of a mermaid swimming through the depths of the ocean. The details of the scales and the colors used to create a realistic underwater atmosphere are truly breathtaking.",
        category: "Fantasy",
        artistInsta: "@mermaidink",
        image: "https://www.example.com/oceanic-dream.jpg",
        rating: 4.5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Wanderlust",
        description: "This tattoo features a beautifully detailed compass with the word 'Wanderlust' inscribed underneath. The intricate linework and shading make this piece truly stand out.",
        category: "Travel",
        artistInsta: "@roaming_ink",
        image: "https://www.example.com/wanderlust.jpg",
        rating: 5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Floral Elegance",
        description: "A stunning bouquet of flowers in a delicate watercolor style. The vibrant colors and intricate details make this tattoo a true work of art.",
        category: "Floral",
        artistInsta: "@bloomingink",
        image: "https://www.example.com/floral-elegance.jpg",
        rating: 4,
        isFeatured: false,
        dateAdded: Date.now(),
    },
    {
        title: "Cosmic Connection",
        description: "A beautifully detailed tattoo featuring the sun, moon, and stars in a cosmic design. The use of black ink and intricate linework create a mesmerizing effect.",
        category: "Space",
        artistInsta: "@cosmic_ink",
        image: "https://www.example.com/cosmic-connection.jpg",
        rating: 4.5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Minimalist Mountains",
        description: "A minimalist tattoo of a mountain range, with clean lines and simple shading. This tattoo is perfect for those who appreciate clean, modern designs.",
        category: "Minimalist",
        artistInsta: "@mountainink",
        image: "https://www.example.com/minimalist-mountains.jpg",
        rating: 4,
        isFeatured: false,
        dateAdded: Date.now(),
    },
    {
        title: "Spiritual Symbols",
        description: "This tattoo features a combination of spiritual symbols from different cultures, including the Om symbol, the Hamsa hand, and a lotus flower. The use of color and shading create a harmonious design.",
        category: "Spiritual",
        artistInsta: "@spiritual_ink",
        image: "https://www.example.com/spiritual-symbols.jpg",
        rating: 4,
        isFeatured: false,
        dateAdded: Date.now(),
    },
    {
        title: "Geometric Wildlife",
        description: "This tattoo features a geometric wolf head with intricate patterns and shapes. The use of bold lines and shading create a unique and striking design.",
        category: "Geometric",
        artistInsta: "@wildink",
        image: "https://www.example.com/geometric-wildlife.jpg",
        rating: 5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Watercolor Dreamcatcher",
        description: "A beautifully designed dreamcatcher with watercolor-style feathers. The vibrant colors and intricate details make this tattoo a true work of art.",
        category: "Watercolor",
        artistInsta: "@dreamcatcherink",
        image: "https://www.example.com/watercolor-dreamcatcher.jpg",
        rating: 4.5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Abstract Landscape",
        description: "A unique tattoo featuring an abstract landscape with geometric shapes and bold colors. The use of shading and linework creates a dynamic and eye-catching design.",
        category: "Abstract",
        artistInsta: "@abstractink",
        image: "https://www.example.com/abstract-landscape.jpg",
        rating: 4,
        isFeatured: false,
        dateAdded: Date.now(),
    },
    {
        title: "Zodiac Constellation",
        description: "A beautifully detailed tattoo featuring the constellation of your zodiac sign. The use of tiny dots and linework create a stunning celestial effect.",
        category: "Astrology",
        artistInsta: "@constellationink",
        image: "https://www.example.com/zodiac-constellation.jpg",
        rating: 4.5,
        isFeatured: true,
        dateAdded: Date.now(),
    }
];


  // Export the seed data to be used in `models/index.js`
  module.exports = tattoos