// Contains the initial, or seed data.
const tattoos = [
    {
        title: "Oceanic Dream",
        description: "A beautiful tattoo of a mermaid swimming through the depths of the ocean. The details of the scales and the colors used to create a realistic underwater atmosphere are truly breathtaking.",
        category: "Fantasy",
        artistInsta: "@mermaidink",
        image: "https://authoritytattoo.com/wp-content/uploads/2020/03/mermaid-tattoo-60.jpg",
        rating: 4.5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Wanderlust",
        description: "This tattoo features a beautifully detailed compass with the word 'Wanderlust' inscribed underneath. The intricate linework and shading make this piece truly stand out.",
        category: "Travel",
        artistInsta: "@roaming_ink",
        image: "https://www.ourmindfullife.com/wp-content/uploads/2022/09/Simple-compass-tattoo-by-@dal.minii_.jpg",
        rating: 5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Floral Elegance",
        description: "A stunning bouquet of flowers in a delicate watercolor style. The vibrant colors and intricate details make this tattoo a true work of art.",
        category: "Floral",
        artistInsta: "@bloomingink",
        image: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81wixAhDmGL.jpg",
        rating: 4,
        isFeatured: false,
        dateAdded: Date.now(),
    },
    {
        title: "Cosmic Connection",
        description: "A beautifully detailed tattoo featuring the sun, moon, and stars in a cosmic design. The use of black ink and intricate linework create a mesmerizing effect.",
        category: "Space",
        artistInsta: "@cosmic_ink",
        image: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81wixAhDmGL.jpg",
        rating: 4.5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Minimalist Mountains",
        description: "A minimalist tattoo of a mountain range, with clean lines and simple shading. This tattoo is perfect for those who appreciate clean, modern designs.",
        category: "Minimalist",
        artistInsta: "@mountainink",
        image: "https://www.ourmindfullife.com/wp-content/uploads/2023/01/Minimalist-mountain-arm-tattoo-by-@kwaycreative.jpg",
        rating: 4,
        isFeatured: false,
        dateAdded: Date.now(),
    },
    {
        title: "Spiritual Symbols",
        description: "This tattoo features a combination of spiritual symbols from different cultures, including the Om symbol, the Hamsa hand, and a lotus flower. The use of color and shading create a harmonious design.",
        category: "Spiritual",
        artistInsta: "@spiritual_ink",
        image: "https://www.lookslikecandy.com/wp-content/uploads/2020/04/91687946_206459963974081_1332594827975920345_n.jpg",
        rating: 4,
        isFeatured: false,
        dateAdded: Date.now(),
    },
    {
        title: "Geometric Wildlife",
        description: "This tattoo features a geometric wolf head with intricate patterns and shapes. The use of bold lines and shading create a unique and striking design.",
        category: "Geometric",
        artistInsta: "@wildink",
        image: "https://brightercraft.com/wp-content/uploads/2018/11/img_4910.jpg",
        rating: 5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Watercolor Dreamcatcher",
        description: "A beautifully designed dreamcatcher with watercolor-style feathers. The vibrant colors and intricate details make this tattoo a true work of art.",
        category: "Watercolor",
        artistInsta: "@dreamcatcherink",
        image: "https://www.cuded.com/wp-content/uploads/2013/09/7-dreamcatcher-side.jpg",
        rating: 4.5,
        isFeatured: true,
        dateAdded: Date.now(),
    },
    {
        title: "Abstract Landscape",
        description: "A unique tattoo featuring an abstract landscape with geometric shapes and bold colors. The use of shading and linework creates a dynamic and eye-catching design.",
        category: "Abstract",
        artistInsta: "@abstractink",
        image: "https://d1kq2dqeox7x40.cloudfront.net/images/posts/nodes_yjeXUyz1Gv.jpg",
        rating: 4,
        isFeatured: false,
        dateAdded: Date.now(),
    },
    {
        title: "Zodiac Constellation",
        description: "A beautifully detailed tattoo featuring the constellation of your zodiac sign. The use of tiny dots and linework create a stunning celestial effect.",
        category: "Astrology",
        artistInsta: "@constellationink",
        image: "https://www.inkedmag.com/.image/t_share/MTYyNjIwMjg1NzkzNjA5NTcw/sagittarius-constellation-tattoo-by-mentat-gamze-728x728.jpg",
        rating: 4.5,
        isFeatured: true,
        dateAdded: Date.now(),
    }
];